export type GenerationHistory = {
  id: string;
  generationType?: "image" | "video" | "audio" | "text";
  nodeId: string;
  projectId?: string;
  modelConfigId?: string;
  modelDisplayName?: string;
  inputMode?: string;
  prompt?: string;
  duration?: number;
  aspectRatio?: string;
  resolution?: string;
  status: "success" | "processing" | "error";
  outputAssetId?: string;
  outputUrl?: string;
  thumbnailUrl?: string;
  posterUrl?: string;
  previewUrl?: string;
  cdnUrl?: string;
  cosUrl?: string;
  downloadableUrl?: string;
  errorMessage?: string;
  createdAt: number;
};
