import type { ImageInputMode, VideoInputMode } from "./model";
import type { OfficialVideoMode } from "./videoModes";

export type WorkflowNodeType = "text" | "textGenerate" | "image" | "imageGenerate" | "video" | "audio" | "script" | "compose" | "director_3d";

export type NodeReference = { sourceNodeId: string; sourceNodeType: string; hint?: string };
export type GenerationPayloadSummary = Record<string, unknown>;

export type TextNodeData = { title: string; content: string; referencedFrom?: NodeReference };
export type TextAgentTask = "prompt-polish" | "script" | "reverse-prompt" | "custom";
export type TextGenerateNodeData = {
  title: string;
  prompt: string;
  modelConfigId?: string;
  taskType: TextAgentTask;
  status: "idle" | "generating" | "success" | "error";
  outputText?: string;
  errorMessage?: string;
  payloadSummary?: GenerationPayloadSummary;
  referencedInputs?: Array<{ sourceNodeId: string; sourceNodeType: string }>;
};
export type ImageNodeData = {
  title: string;
  assetId?: string;
  url?: string;
  cdnUrl?: string;
  cosUrl?: string;
  downloadableUrl?: string;
  localPath?: string;
  thumbnailUrl?: string;
  previewUrl?: string;
  width?: number;
  height?: number;
  aspectRatio?: string;
};
export type ImageGenerateNodeData = {
  title: string;
  prompt: string;
  modelConfigId?: string;
  inputMode: ImageInputMode;
  aspectRatio?: string;
  imageSize?: string;
  imageQuality?: string;
  imageFormat?: string;
  generateCount: number;
  status: "idle" | "generating" | "success" | "error";
  outputAssetId?: string;
  outputUrl?: string;
  url?: string;
  thumbnailUrl?: string;
  cdnUrl?: string;
  cosUrl?: string;
  previewUrl?: string;
  downloadableUrl?: string;
  errorCode?: string;
  errorMessage?: string;
  debugMessage?: string;
  qualityMode?: "full_quality" | "balanced" | "fast";
  payloadSummary?: GenerationPayloadSummary;
  referencedInputs?: Array<{ sourceNodeId: string; sourceNodeType: string }>;
};
export type DirectorVector3 = { x: number; y: number; z: number };
export type DirectorSceneObjectType = "character" | "geometry" | "image_plane" | "product_placeholder";
export type DirectorSceneObject = {
  id: string;
  type: DirectorSceneObjectType;
  subtype?: string;
  name: string;
  position: DirectorVector3;
  rotation: DirectorVector3;
  scale: DirectorVector3;
  material?: { color?: string; opacity?: number };
  assetId?: string;
  assetUrl?: string;
  visible: boolean;
  locked?: boolean;
  labelVisible?: boolean;
};
export type DirectorCamera = {
  id: string;
  name: string;
  position: DirectorVector3;
  target: DirectorVector3;
  fov: number;
  aspectRatio: string;
  thumbnailUrl?: string;
};
export type DirectorSceneSettings = {
  gridVisible: boolean;
  groundVisible: boolean;
  groundOpacity: number;
  skyColor: string;
  sceneScale: number;
  snapToGrid: boolean;
  labelVisible: boolean;
};
export type DirectorScreenshot = {
  id: string;
  projectId?: string;
  nodeId: string;
  cameraId?: string;
  aspectRatio: string;
  imageUrl: string;
  cosKey?: string;
  assetId?: string;
  width: number;
  height: number;
  createdAt: number;
};
export type DirectorScene = {
  id: string;
  projectId?: string;
  nodeId: string;
  objects: DirectorSceneObject[];
  cameras: DirectorCamera[];
  background?: { type: "color" | "image"; color?: string; imageUrl?: string };
  sceneSettings: DirectorSceneSettings;
  screenshots: DirectorScreenshot[];
  createdAt: number;
  updatedAt: number;
};
export type Director3DNodeData = {
  title: string;
  description: string;
  status: "idle" | "editing" | "screenshotting" | "succeeded" | "failed";
  scene?: DirectorScene;
  screenshots?: DirectorScreenshot[];
  outputAssetId?: string;
  outputUrl?: string;
  thumbnailUrl?: string;
  cdnUrl?: string;
  cosUrl?: string;
  downloadableUrl?: string;
  aspectRatio?: string;
  errorMessage?: string;
};
export type AudioNodeData = { title: string; assetId?: string; url?: string; duration?: number };
export type VideoNodeData = {
  title: string;
  prompt: string;
  modelConfigId?: string;
  inputMode: VideoInputMode;
  videoMode?: OfficialVideoMode;
  aspectRatio?: string;
  resolution?: string;
  duration?: number;
  generateCount: number;
  status: "idle" | "generating" | "success" | "completed" | "error";
  generationStartedAt?: number;
  clientRequestId?: string;
  providerTaskId?: string;
  progress?: number;
  assetId?: string;
  outputAssetId?: string;
  outputUrl?: string;
  videoUrl?: string;
  providerVideoUrl?: string;
  thumbnailUrl?: string;
  posterUrl?: string;
  previewUrl?: string;
  cdnUrl?: string;
  cosUrl?: string;
  downloadUrl?: string;
  downloadableUrl?: string;
  errorCode?: string;
  errorMessage?: string;
  debugMessage?: string;
  qualityMode?: "full_quality" | "balanced" | "fast";
  payloadSummary?: GenerationPayloadSummary;
  referencedInputs?: Array<{ sourceNodeId: string; sourceNodeType: string }>;
};
export type ScriptShot = {
  id: string;
  shotNumber: number;
  duration: number;
  visualDescription: string;
  prompt: string;
  subtitle?: string;
  soundDesign?: string;
};
export type ScriptNodeData = { title: string; shots: ScriptShot[] };
export type ComposeNodeData = {
  title: string;
  inputVideoAssetIds: string[];
  inputAudioAssetId?: string;
  subtitleText?: string;
  outputAssetId?: string;
  outputUrl?: string;
  status: "idle" | "composing" | "success" | "error";
  errorMessage?: string;
};
