export type Asset = {
  id: string;
  name: string;
  type: "image" | "video" | "audio" | "text" | "script" | "unknown" | "generated" | "export";
  source: "uploaded" | "generated" | "imported";
  folderId: string | null;
  fileName: string;
  originalName: string;
  localPath: string;
  url: string;
  publicUrl?: string;
  downloadUrl?: string;
  outputUrl?: string;
  cosUrl?: string;
  cdnUrl?: string;
  posterUrl?: string;
  previewUrl?: string;
  downloadableUrl?: string;
  size?: number;
  mimeType?: string;
  width?: number;
  height?: number;
  duration?: number;
  fps?: number;
  thumbnailUrl?: string;
  thumbnailKey?: string;
  posterKey?: string;
  previewKey?: string;
  storageProvider?: string;
  storageKey?: string;
  storageBucket?: string;
  storageRegion?: string;
  storageFileType?: string;
  originalStorageProvider?: string;
  previewStorageProvider?: string;
  publicDeliveryProvider?: string;
  providerId?: string;
  modelId?: string;
  nodeId?: string;
  projectId?: string;
  ownerUserId?: string;
  prompt?: string;
  negativePrompt?: string;
  generationParams?: Record<string, unknown>;
  createdAt: number;
  updatedAt?: number;
};

export type AssetFolder = {
  id: string;
  name: string;
  parentId: string | null;
  projectId?: string;
  ownerUserId?: string;
  createdAt: number;
  updatedAt?: number;
};
